name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this if you're using a different branch (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  # Use GitHub username
        password: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
        registry: ghcr.io  # Ensure we're using GitHub Container Registry (GHCR)

    - name: Build Docker image
      run: |
        docker build --no-cache --progress=plain -t ghcr.io/${{ github.repository_owner }}/dockefileforai:latest .
        docker push ghcr.io/${{ github.repository_owner }}/dockefileforai:latest
