name: Build, Push, and Deploy to Koyeb

on:
  push:
    branches:
      - main  # Change this if your branch is different

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}  
        password: ${{ secrets.GITHUB_TOKEN }}  
        registry: ghcr.io  

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Lint Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile

    - name: Build and Push Docker Image
      run: |
        docker build --no-cache --progress=plain -t ghcr.io/redgale/dockefileforai:latest .
        docker push ghcr.io/redgale/dockefileforai:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Koyeb
      env:
        KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
      run: |
        curl -X POST "https://app.koyeb.com/v1/apps/<YOUR_KOYEB_APP_ID>/deployments" \
          -H "Authorization: Bearer $KOYEB_TOKEN"

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: always
        author_name: 'GitHub Actions'
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
