name: Build, Push, and Deploy to Koyeb

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  
        password: ${{ secrets.GITHUB_TOKEN }}  
        registry: ghcr.io  

    - name: Build and Push Docker Image
      run: |
        docker build --no-cache --progress=plain -t ghcr.io/redgale/dockefileforai:latest .
        docker push ghcr.io/redgale/dockefileforai:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Koyeb
      env:
        KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
      run: |
        curl -X POST "https://app.koyeb.com/v1/apps/<YOUR_KOYEB_APP_ID>/deployments" \
          -H "Authorization: Bearer $KOYEB_TOKEN"
